### ISSUE TITLE
내일 할일

### ISSUE THREAD

**Issue by yujiseok** [bulsazo/youtube-app#60]
- [x] 메인으로 머지 후 배포
- [x] 스타일 다듬기
  - [x] 색상 모드에 따른 글자 색
  - [x] 반응형
- [x] 더미데이터 처리하기...
- [x] 리드미 작성

**Comment by jisooround** [comment]
> * [ ]  메인으로 머지 후 배포
> * [ ]  스타일 다듬기
>   
>   * [ ]  색상 모드에 따른 글자 색
>   * [ ]  반응형
> * [ ]  더미데이터 처리하기...
> * [ ]  리드미 작성
> * [ ] 사이드바 글씨넘치는것 말줄임 처리
